import type { Metadata } from "next";
import "./globals.css";
import { Flowbite } from "flowbite-react";
import { fontSans, fontMono } from "@/lib/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <Flowbite>
      <html lang="en">
        <body
          className={cn(fontSans.variable, fontMono.variable, "antialiased")}
        >
          {children}
        </body>
      </html>
    </Flowbite>
  );
}
